### ISSUE TITLE
Redis namespace

### ISSUE THREAD

**Issue by ghost** [nekipelov/redisclient#14]
How about to move all the staff to kind of "namespace Redis"? For now almost all classes starts with Redis anyway, and namespaces was actually designed to avoid such things.

**Comment by nekipelov** [comment]
You are right. I must to do it.

**Comment by viwiilover** [comment]
hi!skupeiko. nice to meet you! I had some problem when I use this library. when My application run several days,one thread endless loop 。the process explorer show the endless loop is "RedisValue RedisClientImpl::doSyncCommand(const std::vector<RedisBuffer> &buff)".have you ever seen this problem？how to reslove it!

**Comment by nekipelov** [comment]
Done in the develop branch.
