### ISSUE TITLE
Parser Error on Long Bulk Reply 

### ISSUE THREAD

**Issue by ildoonet** [nekipelov/redisclient#15]
in /redisclient/src/redisclient/impl/redisclientimpl.cpp, LINE 208

        for(;;)
        {
            size_t size = socket.read_some(boost::asio::buffer(inbuff));

            for(size_t pos = 0; pos < size;)
            {
                std::pair<size_t, RedisParser::ParseResult> result = 
                    redisParser.parse(inbuff.data() + pos, size - pos);

                if( result.second == RedisParser::Completed )
                {
                    return redisParser.result();
                }
                else if( result.second == RedisParser::Incompleted )
                {
                    continue;     // *** this makes 'pos' variable is not updated!!
                }
                else
                {
                    errorHandler("[RedisClient] Parser error");
                    return RedisValue();
                }

                pos += result.first;
            }
        }

Can you check on this?

(Parse Error does not appear after commenting out that line)

**Comment by nekipelov** [comment]
Fixed. Thank you for the report.
