### ISSUE TITLE
invalid conversion from ‘int64_t {aka long int}’ to ‘const char*’

### ISSUE THREAD

**Issue by Hardy5012** [nekipelov/redisclient#23]
my func is like this:
>  
bool lindex(const std::string& get_key, std::int64_t pos , CallGet&& call_get )
  {
    redis_client_.command("LINDEX", get_key, pos,  boost::bind(&RedisDao::on_lindex, shared_from_this(), call_get, _1));
    return true;
  }
>

complete error:
>error: invalid conversion from ‘int64_t {aka long int}’ to ‘const char*’ [-fpermissive]

How can I set lindex index position?

**Comment by nekipelov** [comment]
Try this:

```cpp
bool lindex(const std::string& get_key, std::int64_t pos , CallGet&& call_get )
{
    redis_client_.command("LINDEX", get_key, std::to_string(pos),
        boost::bind(&RedisDao::on_lindex, shared_from_this(), call_get, _1));
    return true;
}
```

**Comment by Hardy5012** [comment]
OK，thank you! redis suport string prama
