### ISSUE TITLE
redissyncclient.h -> stateValid()

### ISSUE THREAD

**Issue by flyingarg** [nekipelov/redisclient#25]
stateValid() seems be the only way to get the state of a RedisSyncClient connection. 
And it has been marked protected with assert() method inside it. 

Or am i missing some handler that gives one the state of a redis connection ?

**Comment by nekipelov** [comment]
Method stateValid() is for internal use only. Do you want to have getState() or isConnected() method for RedisSyncClient?

**Comment by flyingarg** [comment]
thanks for the prompt reply :-). yup some method like getState() or isConnected() will be nice. Or point me in the direction where this is already available

**Comment by nekipelov** [comment]
Done in the `develop` branch. Added method `state()`.
