### ISSUE TITLE
truely header only solution

### ISSUE THREAD

**Issue by rny** [nekipelov/redisclient#26]
to make this lib truely header only (link without boost libs), the following code is required in one of your cpp file

```
// use boost system error header only
#include <boost/system/detail/error_code.ipp>
```

**Comment by nekipelov** [comment]
1. This file appeared since version 1.56.0. For example Debian stable contains boost version 1.55.0

2. This file is already included in the `boost/system/error_code.hpp` when `BOOST_ERROR_CODE_HEADER_ONLY` is defined.

You can use BOOST_ERROR_CODE_HEADER_ONLY with new boost. But for version 1.55.0 you should use boost with sources:

```
$ ag -C 2 BOOST_ERROR_CODE_HEADER_ONLY
system/error_code.hpp
207-    //  predefined error categories  -----------------------------------------//
208-
209:# ifdef BOOST_ERROR_CODE_HEADER_ONLY
210-    inline const error_category &  system_category() BOOST_SYSTEM_NOEXCEPT;
211-    inline const error_category &  generic_category() BOOST_SYSTEM_NOEXCEPT;
--
513-#include <boost/config/abi_suffix.hpp> // pops abi_prefix.hpp pragmas
514-
515:# ifdef BOOST_ERROR_CODE_HEADER_ONLY
516-#   include <boost/../libs/system/src/error_code.cpp>
517-# endif
```

**Comment by rny** [comment]
i am using boost 1.61.0. 
BOOST_ERROR_CODE_HEADER_ONLY make problems for the current boost version.

e.g. put this line in the header file and **reference this header twice** 

```
#define BOOST_ERROR_CODE_HEADER_ONLY
#include <boost/system/error_code.hpp>
```
compile will failed like this

```
(.bss+0x0): multiple definition of `boost::system::throws'
(.bss+0x0): first defined here
```

I think BOOST_ERROR_CODE_HEADER_ONLY should only work if it is put into one cpp file, but we normally include redisclient in the header files.

**Comment by nekipelov** [comment]
I can't reproduce your problem:
```
~/redisclient/examples$ g++ -std=c++11 benchmark.cpp -I ../src -DBOOST_ERROR_CODE_HEADER_ONLY -o benchmark
~/redisclient/examples$ ldd benchmark
        linux-vdso.so.1 =>  (0x00007ffe2b55f000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efca8cc6000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efca8ab0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efca86e6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efca83dd000)
        /lib64/ld-linux-x86-64.so.2 (0x00005585a6e0b000)
```

**Comment by rny** [comment]
_include twice_

benchmark1.cpp (only one line)
```
#include <redisclient/redisasyncclient.h>
```

result:
···
g++ -std=c++11 benchmark.cpp benchmark1.cpp -I ../src -DBOOST_ERROR_CODE_HEADER_ONLY -o benchmark
/tmp/ccmVAigS.o:(.bss+0x0): multiple definition of `boost::system::throws'
/tmp/ccDx6inr.o:(.bss+0x0): first defined here
/tmp/ccmVAigS.o: In function `redisclient::RedisAsyncClient::state() const':
benchmark1.cpp:(.text+0x91e): multiple definition of `redisclient::RedisAsyncClient::state() const'
/tmp/ccDx6inr.o:benchmark.cpp:(.text+0xa36): first defined here
collect2: error: ld returned 1 exit status
···

**Comment by nekipelov** [comment]
Thanks for a detailed description! Problem with `RedisAsyncClient::state() const` fixed. Try to compile with `BOOST_SYSTEM_NO_DEPRECATED`:

```
$ g++ -std=c++11 benchmark1.cpp benchmark2.cpp -o benchmark  -I../src -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED
$ ldd benchmark
	linux-vdso.so.1 =>  (0x00007fff6fba8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f76ba258000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76ba040000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76b9c78000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76b9970000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f76ba560000)
```

**Comment by rny** [comment]
you are right, define both BOOST_ERROR_CODE_HEADER_ONLY BOOST_SYSTEM_NO_DEPRECATED is the best solution till now.
