### ISSUE TITLE
RedisBuffer pointer storing problem

### ISSUE THREAD

**Issue by janoc** [nekipelov/redisclient#29]
Hello, 

It would be very practical to provide a version of RedisBuffer that would store a copy of the data, not only pointer/reference to it. 

Pointers/references are great to avoid copying, however in the asynchronous case they are an enormous pain to manage. The caller needs to maintain a std::deque<RedisBuffer> of the arguments until completely sure that the request has been executed and the data are not needed anymore. That makes the asynchronous programming much more difficult and bug prone than it needs to be. 

The argument lists is typically converted from some other data when preparing the Redis command anyway, so not copying it doesn't really save anything. If RedisBuffer allowed to copy the data (and thus acted as a true buffer instead of a wrapper), the application wouldn't need to store any temporary data and it would allow a true "fire & forget" Redis command execution.

**Comment by nekipelov** [comment]
Hello.

RedisBuffer not make a copy data because it is already making on the RedisAsyncClient::command before sending command to the queue.

```cpp
void RedisAsyncClient::command(const std::string &cmd, std::deque<RedisBuffer> args,
                          std::function<void(RedisValue)> handler)
{
    if(stateValid())
    {
        args.emplace_front(cmd);

        pimpl->post(std::bind(&RedisClientImpl::doAsyncCommand, pimpl,
                    std::move(pimpl->makeCommand(args)), std::move(handler)));
    }
}

std::vector<char> RedisClientImpl::makeCommand(const std::deque<RedisBuffer> &items)
{
    static const char crlf[] = {'\r', '\n'};

    std::vector<char> result;

    append(result, '*');
    append(result, std::to_string(items.size()));
    append<>(result, crlf);

    for(const RedisBuffer &item: items)
    {
        append(result, '$');
        append(result, std::to_string(item.size()));
        append<>(result, crlf);
        append(result, item);
        append<>(result, crlf);
    }

    return result;
}
```

You can already do "fire & forget" Redis command execution.

PS: It's not intuitive, and I should document this behavior.

**Comment by janoc** [comment]
Well, that doesn't really solve the problem of having to build up a complete temporary data structure so that makeCommand() can copy it. 

I had a code like this:

```c++
std::deque<RedisBuffer> args;
args.emplace_front(key_buf);
for (auto index : result)
{
    std::string index_s = boost::lexical_cast<std::string>(index);
    RedisBuffer index_buf(index_s);
    args.emplace_back(index_buf);
}

m_redis->command("LPUSH", args, std::bind(&RedisLink::result_handler, this, _1));
```

Basically, I am taking some data from `result` and trying to store them in the deque to send to Redis. 
This, of course, fails, because by the time the command is being prepared, the temporaries used to build the individual entries are gone. So with your setup I now have to prepare the entire throw away list of strings (few hundred thousands) in memory so that you can copy them in makeCommand(). 

It would be much more logical if the RedisBuffer kept the actual data already (and you wouldn't need to copy it later!)

**Comment by nekipelov** [comment]
I will think how to solve this problem.

**Comment by janoc** [comment]
Thanks. I have worked the issue around by changing my data representation for now, but I am pretty sure someone else will get tripped up by this as well. Other Redis clients that I have seen collect the arguments into a list/array/something that "owns" them (copies them), so they would likely expect the same.
