### ISSUE TITLE
Core dump in redisclient::RedisSyncClient::connect

### ISSUE THREAD

**Issue by gliatsos** [nekipelov/redisclient#34]
I tried to execute the sync_set_get example in a machine (tried to connect to 127.0.0.1) where no Redis is installed and I got the following core dump:

Can't connect to redis: 
*** Error in `./sync_set_get': free(): invalid pointer: 0x0000000001ccc448 ***
Aborted (core dumped)

I guess it should have returned the error message without core dump, unless I did something wrong.

**Comment by nekipelov** [comment]
Hello. Thank you for report, but I can not reproduce:

```
$ sudo /etc/init.d/redis-server stop
[ ok ] Stopping redis-server (via systemctl): redis-server.service.
$ ./sync_set_get
Can't connect to redis: Connection refused
```

Please show me:

 * boost version
 * gcc version
 * linux distribution
 * callstack from gdb 
 * strace output

**Comment by gliatsos** [comment]
Thank for our fast response.

- boost version: 1.55
- gcc version: 5.2.0
- linux distribution: xubuntu 15.04
- gdb 
(gdb) backtrace 
#0  0x00007ffff6b78267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6b79eca in __GI_abort () at abort.c:89
#2  0x00007ffff6bbbc53 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6cd41a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6bc3c69 in malloc_printerr (ptr=<optimized out>, str=0x7ffff6cd02fa "free(): invalid pointer", action=1) at malloc.c:4965
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
#5  0x00007ffff6bc789c in __GI___libc_free (mem=<optimized out>) at malloc.c:2950
#6  0x000000000040b5cc in main ()

By the way, shall I use the redisclient in a multithreaded process? Is it thread safe? Can I use the RedisSyncClient with one global connection? Or should I go for RedisAsyncClient?

Thank you in advance,
George

**Comment by nekipelov** [comment]
Are you using boost from ubuntu compiled with gcc-4.x? It is incompatible with gcc-5 ABI. Simple test:

```
$ cat test.cc
#include <boost/system/error_code.hpp>
#include <iostream>

int main() 
{
	boost::system::error_code ec;
	std::cout << ec.message() << "\n";
	
	return 0;
}
$ g++ --version
g++ (Ubuntu 5.1.1-4ubuntu12) 5.1.1 20150504
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ test.cc -lboost_system && ./a.out
Success�*** Error in `./a.out': free(): invalid pointer: 0x0000000002388c68 ***
Aborted (core dumped)
```

> Is it thread safe? Can I use the RedisSyncClient with one global connection? Or should I go for RedisAsyncClient?

Is not thread-safe. Use locks, connection per thread or special thread.

**Comment by gliatsos** [comment]
Thank you for your response. You are right, no problem on redisclient.

> Is not thread-safe. Use locks, connection per thread or special thread.

Will it be a problem, having a shared RedisSyncClient (common connection) used by multithreaded process? Each thread will execute different commands to Redis.

**Comment by nekipelov** [comment]
> Will it be a problem, having a shared RedisSyncClient (common connection) used by multithreaded process? Each thread will execute different commands to Redis.

No, if you use the lock for any calls.
