### ISSUE TITLE
Pipeline commands support?

### ISSUE THREAD

**Issue by grisharav** [nekipelov/redisclient#35]
Hi, thanks for the great work on this.
I am wondering, if it's possible to support pipelining of commands, similar to what the hiredis (https://github.com/redis/hiredis#pipelining) supports?
What I'm looking for is a way to perform a lot of hmget (or hgetall) commands. Currently if I understand correctly, the only way to do this is to chain callbacks for each command with the next command. Is there any other way that you can suggest to achieve this?

Thanks a lot,
Greg

**Comment by nekipelov** [comment]
Currently pipilening is not supported. To perfom a lot of commands (hmget or hgetall) you can use lua: http://redis.io/commands/EVAL.

**Comment by nekipelov** [comment]
Fixed in version 0.6
