### ISSUE TITLE
Use Lua script with EVAL command in RedisClient

### ISSUE THREAD

**Issue by gliatsos** [nekipelov/redisclient#37]
Hi, 

I am trying to perform multiple command by using EVAL and a Lua script but with no luck. Could you please provide an example?

More specific, I am trying to retrieve multiple hashes like below:
redis-cli --ldb --eval /tmp/script.lua hash_key1 hash_key2

where script.lua:
local r = {}
for _, v in pairs(KEYS) do
    r[#r+1] = redis.call('HGETALL', v)
end
return r

Can the above be achieved by using RedisClient?

I tried something below:
redisclient.command("EVAL", {"/tmp/script.lua", hash_key1, hash_key2}
but obviously is wrong.

Thank you in advance,
George

**Comment by nekipelov** [comment]
Hi. Redis server does not work with lua files: https://redis.io/commands/eval. Command `redis-cli --ldb --eval /tmp/script.lua hash_key1 hash_key2` reads file /tmp/script.lua and creates **EVAL** command.

Right way:

```c++
    const std::string hash_key1 = "hash-key-1";
    const std::string hash_key2 = "hash-key-2";
    const unsigned int num_keys = 0;
    const std::string script = R"*(
local r = {}
for i = 1, #ARGV do
        r[#r+1] = redis.call('HGETALL', ARGV[i])
end
return r
)*";

     redis.command("EVAL",  {
            script,
            std::to_string(num_keys),
            hash_key1,
            hash_key2});
```

**Comment by gliatsos** [comment]
Thank you for the quick response!
