### ISSUE TITLE
parseArray in redisparser is too slow

### ISSUE THREAD

**Issue by yagilofir** [nekipelov/redisclient#38]
Hi.
First I want to thank you for this great library, we are using it for writing lots of data in our system and it does the job quite well.
Recently we changed a non-efficient loop of 1000 hmget's in our code (each hash contains 3 elements) to a Lua script which returns one big array (size of 3000), and we run this script using your evalsha implementation. Then we parse the result.
After profiling, it turned out that before the change, it took 87ms for the loop to run.
After the change, the evalsha command took ~230ms (results are 3 times worse than the ridiculous 1000 hmget loop solution). It turned out that 99% of the overhead comes from the parseArray method inside the redisparser.cpp file.

Do you plan anytime soon to improve this parser?
We did the same improvement in our C# program (with StackExchange evalsha) and the results there are almost 300 times faster (obviously that's because we do only one redis call instead of 1000 calls, and the StackExchange evalsha command is very efficient.)

Thanks.

**Comment by nekipelov** [comment]
Hi. Thanks for feedback. 

You are right, parseArray is slow. I will try to improve it when I will have free time.

**Comment by nekipelov** [comment]
Fixed in version 0.6
