### ISSUE TITLE
[RedisClient] unexpected message: OK

### ISSUE THREAD

**Issue by yanyan147** [nekipelov/redisclient#4]
terminate called after throwing an instance of 'std::runtime_error'
  what():  [RedisClient] unexpected message: OK
make: *** [run] Aborted (core dumped)

When I send commands async quickly, redisclient crash with the above error. The error is gone if I pause for a few millisec after each command. Any idea? The code is based on example1.cpp.

The "OK" within "unexpected message: OK" looks like a proper server reply that the driver didn't expect.

I am using the software below:
redis-3.0.0-rc1.tar.gz
centos 7 fully updated
boost 1.53 (comes w/ centos 7)
gcc 482 (comes w/ centos 7)
redisclient version
commit 96e2f602ed8010591bbf3fc842810ec0ea59a15c
Date:   Thu Nov 13 11:57:16 2014 +0300

==> code.zip.base64 <==
UEsDBBQAAAAIABG8nUVDPMxUNAEAAMADAAAIABwATWFrZWZpbGVVVAkAAxJ0oVQSdKFUdXgLAAEE
6AMAAAQBAgAAlVNNT4NAED0zv2IONIE0u5WvC7GJVqPWkGLSg/WiQbrqAQph16T+e6EwhXQ1oRd4
zL5582aYjZaLNc6RZe9FIdWb/JFK5MdP9VWJZMtyBdHtXXR9f6B+Ios4R1a2p3Cz2QzPYhfZc5Jl
9VPsVZUgW3I+k1XaEB3nlCrVdp5Op47zXxZU37sQlZDqwgWDzzoE7TtE04oXj2u7Y/ACDNOqK9lo
viIr0LzCmtLZtxtYd2wDsUmZp2XZZ1rUk40sRfOyFQKoDYYo9kleZkICgWPIIeAS8Aj4BAKgPKf3
TpGx7nt+X3tcB2RQqz16ciThaRLeuRK+JuGfKxFoEsFoiUkzvok+t25JTyaXZiLZhWBU9fX4+OPP
6UvQx9zBiPTV6GP+oInBwvCnh3j1EmJzP2jp8OAHfgFQSwMEFAAAAAgAjT6eRSIGGPWpBAAAcQ4A
AAoAHAB0ZXN0MDIuY3BwVVQJAAM66aFUPemhVHV4CwABBOgDAAAEAQIAALVWbVPjNhD+XP+KPd80
tTmTF/pyUwf4klLKQHsdctN+9Ci2QjQ4kk9S6FGG/96VZCdK7OQ4ZmqGWF6tVtrnWe3uW8bzclVQ
OFVaMn53HrxdS5hAGSXLbdmScFb5opIp7X+r9qpcsyX1BTOBtgdEMTFg1YAUhaRK9RdV1VaaMV50
z+gF7tOak7RgKi8Z5XrgjfuL8yBQmmiWQy640qB0kabOa7CK1/QRziBccfZpRY+t6PiePh7Tz2RZ
lTQcf2H9X6Rc0ZaFByPFtUFeEqXgbyHvqQyegmo1K1meBoCPE0bWrTQ1sKQpE5mi8oHlFHpMTN0w
gVtjdGJdgp7cfMTWkHlSWKtH61GcgKcctRY+PQf2/SBYAYJPBOc01+ZEpXHXfNAi6fC8R6UU8nek
j9zReOwbmVIduQW3G3h6Fo9txcuXKSotqggFQSXZA9HUYfdl0JyJfcCNg2c0aTdwNKTp6/1HXsFN
52Kl4fQUsuzXq5uLLDPjMA2d6Obqj0a0AdvO2bWUF6U7NJtH8Ga9P9Rcral2O+EJrKkJ4d/p5rSg
hWM8BWvYP6az/Wx/aanojlUPnH4ulnjhiyicXnwME1hflMQL+WS9suup+THXOOptEMbgSEAvmEog
G8Vxc6TnFhWHouhVcKPBNtRfZ8SK7BH6WkxtIERxB32DgWWwpXmGSeLDdVjziVpPzWAv/pc7+PsL
vgL2yy7Y0cxzM1jHw+6ptmPtiqNTyJN1DeZSLLei7WXYdNF9KBe8iu7LLrr3U/PmzE/m3QT9L1A0
o072f7m4CZOXkb9F/J7kaLKXqJJGV9K5VylMVDS8FILrCZE06kh8jhNTOazq8nFaUlpFpcDJpaJ5
bEGrtzAhl7mCjRasYj1TCcU+Z6ZBSNMlK7GboLhZoSJrw57FZf9HnjtYfkNISiyXu2HSgwe351aI
hMVMsX/pmSNjPxHosttIU6Ujr1r0wHUQyQtKjdt/MMh3+JuXK7UgZRnaG8ewBHFsFEbD4fBoNDz5
oRHOSa6FNDNGYpHUQ/zMS5HfR3btXMjIqBIUD8f4OgU+hnfvSFzHqHXJ9GSnHlvnQOSdctHWWJg5
CzO04PY1ZmbxuhB4y11HB/cm71vax7UOSizG+M4swMR+uvGs0XI3w0zY0QFNc8p+hVhlM4Ieo9k+
7h01iaql4C6Xr+IS2S7+GEsaL5BZvcl5tiQCU3AnOMVsAAwqslIUj1YyrUvqJQry7WgY+1mgCXcU
byVRe5Edc6Nt5gqBHR+FQqPYjSM9OtZodgCTmw+T62n258VtNr2YwJENDW+RxHYHl3GcqWNkgIZa
hSvkLsz5VmwH35jz2aug3XyhuxXsNpZP0JXaTZvomombJWHcBBB2Qwsi4ejI5WWomyMnrFt60w2P
Tt73h/g3CseemrFUCWnA+On79z+Pg4PN3IFezlHt5a+x11LDP66z9hpop19rbe9XYZ7KK+tuJcwB
m0HU0qv9S1OT7zN3S6JaiL228SyufapjkdgEVveVjeFkX52uFRPoOQ9Mucb/ExPmW1C5nLoB6KP9
jl5WBeSKJ372qlFpYvvHYRPch/MZuJzZpEmfCjsrqV5JjskGQ+g/UEsBAh4DFAAAAAgAEbydRUM8
zFQ0AQAAwAMAAAgAGAAAAAAAAQAAAO2BAAAAAE1ha2VmaWxlVVQFAAMSdKFUdXgLAAEE6AMAAAQB
AgAAUEsBAh4DFAAAAAgAjT6eRSIGGPWpBAAAcQ4AAAoAGAAAAAAAAQAAAO2BdgEAAHRlc3QwMi5j
cHBVVAUAAzrpoVR1eAsAAQToAwAABAECAABQSwUGAAAAAAIAAgCeAAAAYwYAAAAA

**Comment by nekipelov** [comment]
Fixed in commit 69c4c9086dbd87305be1e476044d67dc368bad6d. Thank you for report.
