### ISSUE TITLE
How can I use hgetall to get the data?

### ISSUE THREAD

**Issue by TracyDa** [nekipelov/redisclient#42]
I read the example, but can't find a way to get all fields and values of the hash. If I stored many fields and values, it's inefficient to get only one value, so can you give us an example to return all fields.

Thanks.

**Comment by nekipelov** [comment]
```
std::vector<redisclient::RedisValue> hash = redis.command("HGETALL", {"hash-name"}).toArray();

for(size_t i = 0; i < hash.size(); i += 2)
{
	std::string name = hashData.at(i).toString();
	std::string value = hashData.at(i + 1).toString();

	std::cerr << name << ": " << value << "\n";
}
```

full exaple: https://gist.github.com/nekipelov/3bfb93b58b397ae2b349706b324ad832

**Comment by TracyDa** [comment]
Many thanks for your quick response, it works. 

By the way, if I use 
`result = redis.command("HGETALL", {"user2"});` to try to get the value, although there is no key named `user2`,  and `result.isOk()` returns true, but `result.toString()` is an empty string, is this ok?

**Comment by nekipelov** [comment]
Yes, it is ok. isError() will return true only when Redis gives error.
