### ISSUE TITLE
Shall there be a formal release of the library with new features?

### ISSUE THREAD

**Issue by grisharav** [nekipelov/redisclient#47]
Hey, thanks for the great work.
I saw that lately there were some fixes and improvements to the library, are you planning a release/tag?

I would rather work with a formal release instead of the "current latest"

Thanks
Greg

**Comment by nekipelov** [comment]
Yes,  I am planning it. When I will have free time.

**Comment by nekipelov** [comment]
Done: https://github.com/nekipelov/redisclient/releases/tag/v0.5.2.

**Comment by grisharav** [comment]
Thanks a lot!

**Comment by grisharav** [comment]
Hey, I saw that the updated library version is 0.6 now, but there is no release appearing for it. Is there one planned?

**Comment by nekipelov** [comment]
Yes it's done. But version 1.0.0 is not planned in the near time.

**Comment by grisharav** [comment]
Thanks, I saw you marked it as pre-release, intentional?

**Comment by nekipelov** [comment]
Yes.
