### ISSUE TITLE
Integrating into node.native

### ISSUE THREAD

**Issue by minixxie** [nekipelov/redisclient#5]
Dear Sir,

This library is amazing, and I'm trying to use it in node.native project (node.js c++ port).
since they are both event-driven, I don't know where to put the ioService.run() code. (maybe due to my poor understanding of boost asio), please help:
        ioService.run();
    return native::run();
The above 2 lines are both blocking function calls.

        int main()
            {
                boost::asio::ip::address redisAddress = boost::asio::ip::address::from_string("127.0.0.1");
            const int redisPort = 6379;

            boost::asio::io_service ioService;
            RedisClient redis(ioService);

            if( !redis.connect(redisAddress, redisPort) )
            {
                std::cerr << "Can't connecto to redis" << std::endl;
                return EXIT_FAILURE;
            }

            http server;
            int port = 8080;
            if(!server.listen("0.0.0.0", port, [&redis, &ioService](request& req, response& res) {
                if ( req.url().path() == "/user/create" ) user::create(req, res, redis, ioService);//some function doing redis access and out http response
                else
                {
                        res.set_status(404);
                        res.end("404 Not Found");
                }

            })) return 1; // Failed to run server.

            std::cout << "Server running at http://0.0.0.0:" << port << "/" << std::endl;
                ioService.run();
            return native::run();
        }

Thanks & Regards,
Simon

**Comment by nekipelov** [comment]
I do not know how to do it. I think you should use http server with boost::asio event loop (https://github.com/nekipelov/hserv) or redis library with libuv event loop (https://github.com/redis/hiredis).
