### ISSUE TITLE
Performance improvements question

### ISSUE THREAD

**Issue by grisharav** [nekipelov/redisclient#54]
Hi,
In `Redisvalue` class you have methods to retrieve the underlying data, such as: 
```
    // Return the value as a std::string if
    // type is a byte string; otherwise returns an empty std::string.
    REDIS_CLIENT_DECL std::string toString() const;

    // Return the value as a std::vector<char> if
    // type is a byte string; otherwise returns an empty std::vector<char>.
    REDIS_CLIENT_DECL std::vector<char> toByteArray() const;

    // Return the value as an array if type is an array;
    // otherwise returns an empty array.
    REDIS_CLIENT_DECL std::vector<RedisValue> toArray() const;
```
Any reason they don't return a const& to the underlying data (stored in the variant)? It would prevent a potentially unnecessary copy of the data. In addition there is a:
```
   REDIS_CLIENT_DECL std::vector<RedisValue> &getArray();
```
Any reason that there is no const overload?

**Comment by nekipelov** [comment]
> Any reason they don't return a const& to the underlying data (stored in the variant)? It would prevent a potentially unnecessary copy of the data.

1. Internal data are stored as std::vector<char>. I can't return std::string as reference because I create temporary object.

2. This code also return temporary object:
```template<typename T>
T RedisValue::castTo() const
{
    if( value.type() == typeid(T) )
        return boost::get<T>(value);
    else
        return T();
}
```

**Comment by grisharav** [comment]
I don't quite follow, I see:
```
boost::variant<NullTag, int64_t, std::vector<char>, std::vector<RedisValue> > value;
```
in the `RedisValue` class, which means you store the data not as an std::vector but as a variant.
If you do a boost::get you can get a reference (http://www.boost.org/doc/libs/1_66_0/doc/html/boost/get.html) to the underlying data member, this means we can potentially get references to any of the variant types without copies.
Indeed the way the castTo is written it can't return a reference (due to the else clause), but even if you simply grant user access to the (const) variant member, it can speed up the users code.

**Comment by nekipelov** [comment]
How do you propose to implement the toString() method?

**Comment by grisharav** [comment]
No way to return a reference to an object that you don't hold, but we definitely can return a reference to `std::vector<char>` and `std::vector<RedisValue>` and if a user cares about the performance she can use the `std::vector<char>` as a string. We already have a `std::vector<RedisValue> &getArray();` but there is no const overload...

**Comment by nekipelov** [comment]
What methods do you want?

* getArray()/getArray() const
* getByteArray()/getByteArray() const
* what more?

**Comment by grisharav** [comment]
Those sounds right. Other values are small and should be copied.

**Comment by nekipelov** [comment]
Done in the master branch.
