### ISSUE TITLE
Use the asio function to replace ":poll"

### ISSUE THREAD

**Issue by feihongmeilian** [nekipelov/redisclient#58]
I replaced the boost.asio with non-boost asio，

I found that redisclient cannot run under the windows platform because it calls the poll function.

So I replaced the poll function with the related function in asio

Here is my realization：

//redisclientimpl.cpp

        size_t socketReadSome(asio::generic::stream_protocol::socket &socket, asio::mutable_buffer buffer,
		const std::chrono::milliseconds &timeout,
		std::error_code &ec)
	{
		asio::detail::buffer_sequence_adapter<asio::mutable_buffer, asio::mutable_buffer> buf(buffer);
		if (socket.native_handle() == asio::detail::invalid_socket)
		{
			ec = asio::error::bad_descriptor;
			return 0;
		}

		auto bytes = asio::detail::socket_ops::recv(socket.native_handle(), buf.buffers(), buf.count(), 0, ec);
		if (bytes > 0)
		{
			return bytes;
		}
		else if (bytes == 0)
		{
			ec = asio::error::eof;
			return 0;
		}

		if (ec != asio::error::would_block && ec != asio::error::try_again)
			return 0;

		if (asio::detail::socket_ops::poll_read(socket.native_handle(),
			asio::detail::socket_ops::internal_non_blocking, timeout.count(), ec) < 0)
		{
			return 0;
		}
		return socket.read_some(buffer, ec);	
	}

	size_t socketWrite(asio::generic::stream_protocol::socket &socket, asio::const_buffer buffer,
		const std::chrono::milliseconds &timeout, std::error_code &ec)
	{
		asio::detail::buffer_sequence_adapter<asio::const_buffer, asio::const_buffer> buf(buffer);
		if (socket.native_handle() == asio::detail::invalid_socket)
		{
			ec = asio::error::bad_descriptor;
			return 0;
		}

		if (buf.all_empty())
		{
			ec = asio::error_code();
			return 0;
		}

		auto bytes = asio::detail::socket_ops::send(socket.native_handle(), 
			buf.buffers(), buf.count(), 0, ec);
		if (bytes==0 || bytes==buf.total_size())
		{
			return bytes;
		}
		else if (bytes < 0 && (ec != asio::error::would_block || ec != asio::error::try_again))
		{
			return 0;
		}
		else
		{
			socket.set_option(asio::ip::tcp::socket::send_low_watermark(buf.total_size() - bytes));

			const auto result = asio::detail::socket_ops::poll_write(socket.native_handle(),
				asio::detail::socket_ops::internal_non_blocking, timeout.count(), ec);
			if (result > 0)
			{
				socket.write_some(asio::buffer(asio::buffer_cast<const char *>(buffer) + bytes, buffer.size()), ec);
				bytes = buffer.size();
			}
			socket.set_option(asio::ip::tcp::socket::send_low_watermark(1));
			return bytes;
		}
	}

//redissyncclient.cpp

void RedisSyncClient::connect(const asio::ip::tcp::endpoint &endpoint, std::error_code &ec)
{
	pimpl->socket.open(endpoint.protocol(), ec);
        if (!ec && tcpNoDelay)
            pimpl->socket.set_option(asio::ip::tcp::no_delay(true), ec);

        // TODO keep alive option

	pimpl->socket.non_blocking(true);

	asio::detail::socket_ops::connect(pimpl->socket.native_handle(), endpoint.data(), endpoint.size(), ec);
	if (ec != asio::error::in_progress
		&& ec != asio::error::would_block)
	{
		return;
	}

	if (asio::detail::socket_ops::poll_connect(pimpl->socket.native_handle(), connectTimeout.count(), ec) < 0)
		return;

	int connect_error = 0;
	size_t connect_error_len = sizeof(connect_error);
	if (asio::detail::socket_ops::getsockopt(pimpl->socket.native_handle(), 0, SOL_SOCKET, SO_ERROR,
		&connect_error, &connect_error_len, ec) == asio::detail::socket_error_retval)
		return;

	ec = asio::error_code(connect_error,
		asio::error::get_system_category());

    if (!ec)
        pimpl->state = State::Connected;
}

**Comment by nekipelov** [comment]
Yes the redisclient has this kind of problem. But your implementation use internal code boost::asio. It can be broken at any time.

Currently you can use version https://github.com/nekipelov/redisclient/releases/tag/v0.6.0.
