### ISSUE TITLE
boost version

### ISSUE THREAD

**Issue by puppetMaster3** [nekipelov/redisclient#7]
what version of boost are you using?

latest one is giving arg issues.

**Comment by nekipelov** [comment]
I'm using miscellaneous boost versions. Please show your compiler messages.

**Comment by puppetMaster3** [comment]
Can you please send me your email address to vic (at) apakau dot com and I'll send you a cmake project.

**Comment by nekipelov** [comment]
My email: alex@nekipelov.net
