### ISSUE TITLE
Can't Execute command when subscribed to a topic

### ISSUE THREAD

**Issue by kelliott121** [nekipelov/redisclient#78]
The `command` member function of the async client checks `stateValid()` before executing. `Connected` is currently the only state that qualifies as valid, so command throws an exception when the client is in the `Subscribed` state. Is this an intentional limitation and if not, could it be fixed to count both states as valid?

**Comment by nekipelov** [comment]
This is a redis server design.

**Comment by kelliott121** [comment]
That's what I assumed. Thank you for the prompt response!
